package rune2image

import (
	"image"
)

func PlotFontLine(s string, x, y int, m *image.Image) {
	return
}

func Image(l rune) (*image.Image, error) {
	// see palgen/convert.go. Create an image with an image.New function
	c image.Image
	switch l {
	case "a":
		PlotFontLine("***-", x+1, y+1, c)
		PlotFontLine("--**", x+1, y+2, c)
		PlotFontLine("-****", x, y+3, c)
		PlotFontLine("**-**-", x, y+4, c)
		PlotFontLine("-**-**", x, y+5, c)
	case "A":
		PlotFontLine("-**-", x+1, y, c)
		PlotFontLine("-****-", x, y+1, c)
		PlotFontLine("**--**", x, y+2, c)
		PlotFontLine("******", x, y+3, c)
		PlotFontLine("**--**", x, y+4, c)
		PlotFontLine("**  **", x, y+5, c)
	case "b":
		PlotFontLine("***", x, y, c)
		PlotFontLine("-**-", x, y+1, c)
		PlotFontLine("****-", x+1, y+2, c)
		PlotFontLine("** **", x+1, y+3, c)
		PlotFontLine("-**-**", x, y+4, c)
		PlotFontLine("**-**-", x, y+5, c)
	case "B":
		PlotFontLine("*****-", x, y, c)
		PlotFontLine("-**-**", x, y+1, c)
		PlotFontLine("****-", x+1, y+2, c)
		PlotFontLine("** **", x+1, y+3, c)
		PlotFontLine("-** **", x, y+4, c)
		PlotFontLine("*****-", x, y+5, c)
	case "c":
		PlotFontLine("-****-", x, y+1, c)
		PlotFontLine("**--**", x, y+2, c)
		PlotFontLine("** ---", x, y+3, c)
		PlotFontLine("**--**", x, y+4, c)
		PlotFontLine("-****-", x, y+5, c)
	case "C":
		PlotFontLine("-****-", x, y, c)
		PlotFontLine("**- -*", x, y+1, c)
		PlotFontLine("**", x, y+2, c)
		PlotFontLine("**", x, y+3, c)
		PlotFontLine("**- -*", x, y+4, c)
		PlotFontLine("-****-", x, y+5, c)
	case "d":
		PlotFontLine("***", x+3, y, c)
		PlotFontLine("-**", x+3, y+1, c)
		PlotFontLine("-*****", x, y+2, c)
		PlotFontLine("**--**", x, y+3, c)
		PlotFontLine("**  **", x, y+4, c)
		PlotFontLine("-***-*", x, y+5, c)
	case "D":
		PlotFontLine("****-", x, y, c)
		PlotFontLine("**-**-", x, y+1, c)
		PlotFontLine("** -**", x, y+2, c)
		PlotFontLine("** -**", x, y+3, c)
		PlotFontLine("**-**-", x, y+4, c)
		PlotFontLine("****-", x, y+5, c)
	case "e":
		PlotFontLine("-****-", x, y+1, c)
		PlotFontLine("** -**", x, y+2, c)
		PlotFontLine("******", x, y+3, c)
		PlotFontLine("**-", x, y+4, c)
		PlotFontLine("-****-", x, y+5, c)
	case "E":
		PlotFontLine("-*****", x, y, c)
		PlotFontLine("**---*", x, y+1, c)
		PlotFontLine("****-", x, y+2, c)
		PlotFontLine("**--", x, y+3, c)
		PlotFontLine("**- **", x, y+4, c)
		PlotFontLine("*****-", x, y+5, c)
	case "f":
		PlotFontLine("-***-", x+1, y, c)
		PlotFontLine("-**--*", x, y+1, c)
		PlotFontLine("****", x, y+2, c)
		PlotFontLine("-**-", x, y+3, c)
		PlotFontLine("**", x+1, y+4, c)
		PlotFontLine("****", x, y+5, c)
	case "F":
		PlotFontLine("*****-", x, y, c)
		PlotFontLine("**--**", x, y+1, c)
		PlotFontLine("**-", x, y+2, c)
		PlotFontLine("****", x, y+3, c)
		PlotFontLine("**-", x, y+4, c)
		PlotFontLine("*-", x, y+5, c)
	case "g":
		PlotFontLine("-**-**", x, y+1, c)
		PlotFontLine("** **-", x, y+2, c)
		PlotFontLine("-****", x, y+3, c)
		PlotFontLine("-**", x+2, y+4, c)
		PlotFontLine("****-", x, y+5, c)
	case "G":
		PlotFontLine("-****-", x, y, c)
		PlotFontLine("**--**", x, y+1, c)
		PlotFontLine("**", x, y+2, c)
		PlotFontLine("** ***", x, y+3, c)
		PlotFontLine("**--**", x, y+4, c)
		PlotFontLine("-***-*", x, y+5, c)
	case "h":
		PlotFontLine("***", x, y, c)
		PlotFontLine("-**-", x, y+1, c)
		PlotFontLine("****-", x+1, y+2, c)
		PlotFontLine("**-**", x+1, y+3, c)
		PlotFontLine("-** **", x, y+4, c)
		PlotFontLine("*** **", x, y+5, c)
	case "H":
		PlotFontLine("**  **", x, y, c)
		PlotFontLine("**--**", x, y+1, c)
		PlotFontLine("******", x, y+2, c)
		PlotFontLine("**--**", x, y+3, c)
		PlotFontLine("**  **", x, y+4, c)
		PlotFontLine("**  **", x, y+5, c)
	case "i":
		PlotFontLine("**", x+2, y, c)
		PlotFontLine("--", x+2, y+1, c)
		PlotFontLine("***", x+1, y+2, c)
		PlotFontLine("-**", x+1, y+3, c)
		PlotFontLine("-**-", x+1, y+4, c)
		PlotFontLine("****", x+1, y+5, c)
	case "I":
		PlotFontLine("****", x+1, y, c)
		PlotFontLine("-**-", x+1, y+1, c)
		PlotFontLine("**", x+2, y+2, c)
		PlotFontLine("**", x+2, y+3, c)
		PlotFontLine("-**-", x+1, y+4, c)
		PlotFontLine("****", x+1, y+5, c)
	case "j":
		PlotFontLine("**", x+3, y, c)
		PlotFontLine("--", x+3, y+1, c)
		PlotFontLine("***", x+2, y+2, c)
		PlotFontLine("-**", x+2, y+3, c)
		PlotFontLine("**-**", x, y+4, c)
		PlotFontLine("-***-", x, y+5, c)
	case "J":
		PlotFontLine("****", x+2, y, c)
		PlotFontLine("-**-", x+2, y+1, c)
		PlotFontLine("**", x+3, y+2, c)
		PlotFontLine("** **", x, y+3, c)
		PlotFontLine("**-**", x, y+4, c)
		PlotFontLine("-***-", x, y+5, c)
	case "k":
		PlotFontLine("***", x, y, c)
		PlotFontLine("-**", x, y+1, c)
		PlotFontLine("**-**", x+1, y+2, c)
		PlotFontLine("****-", x+1, y+3, c)
		PlotFontLine("-**-**", x, y+4, c)
		PlotFontLine("*** **", x, y+5, c)
	case "K":
		PlotFontLine("***-**", x, y, c)
		PlotFontLine("-****-", x, y+1, c)
		PlotFontLine("***-", x+1, y+2, c)
		PlotFontLine("****-", x+1, y+3, c)
		PlotFontLine("-**-**", x, y+4, c)
		PlotFontLine("*** **", x, y+5, c)
	case "l":
		PlotFontLine("***", x+1, y, c)
		PlotFontLine("-**", x+1, y+1, c)
		PlotFontLine("**", x+2, y+2, c)
		PlotFontLine("**", x+2, y+3, c)
		PlotFontLine("-**-", x+1, y+4, c)
		PlotFontLine("****", x+1, y+5, c)
	case "L":
		PlotFontLine("****", x, y, c)
		PlotFontLine("-**-", x, y+1, c)
		PlotFontLine("**", x+1, y+2, c)
		PlotFontLine("**", x+1, y+3, c)
		PlotFontLine("-**--*", x, y+4, c)
		PlotFontLine("******", x, y+5, c)
	case "m":
		PlotFontLine("**-**-", x, y+1, c)
		PlotFontLine("-*****", x, y+2, c)
		PlotFontLine("*-*-*", x+1, y+3, c)
		PlotFontLine("*-*-*", x+1, y+4, c)
		PlotFontLine("*-*-*", x+1, y+5, c)
	case "M":
		PlotFontLine("**-**", x+1, y, c)
		PlotFontLine("**-**", x+1, y+1, c)
		PlotFontLine("*-*-*", x+1, y+2, c)
		PlotFontLine("*- -*", x+1, y+3, c)
		PlotFontLine("*- -*", x+1, y+4, c)
		PlotFontLine("*   *", x+1, y+5, c)
	case "n":
		PlotFontLine("**-**-", x, y+1, c)
		PlotFontLine("-*****", x, y+2, c)
		PlotFontLine("**-**", x+1, y+3, c)
		PlotFontLine("** **", x+1, y+4, c)
		PlotFontLine("** **", x+1, y+5, c)
	case "N":
		PlotFontLine("**  **", x, y, c)
		PlotFontLine("**- **", x, y+1, c)
		PlotFontLine("***-**", x, y+2, c)
		PlotFontLine("**-***", x, y+3, c)
		PlotFontLine("** -**", x, y+4, c)
		PlotFontLine("**  **", x, y+5, c)
	case "o":
		PlotFontLine("-****-", x, y+1, c)
		PlotFontLine("**--**", x, y+2, c)
		PlotFontLine("**  **", x, y+3, c)
		PlotFontLine("**--**", x, y+4, c)
		PlotFontLine("-****-", x, y+5, c)
	case "O":
		PlotFontLine("-****-", x, y, c)
		PlotFontLine("**--**", x, y+1, c)
		PlotFontLine("**  **", x, y+2, c)
		PlotFontLine("**  **", x, y+3, c)
		PlotFontLine("**--**", x, y+4, c)
		PlotFontLine("-****-", x, y+5, c)
	case "p":
		PlotFontLine("**-**-", x, y+1, c)
		PlotFontLine("-**--*", x, y+2, c)
		PlotFontLine("****", x+1, y+3, c)
		PlotFontLine("-**-", x, y+4, c)
		PlotFontLine("****", x, y+5, c)
	case "P":
		PlotFontLine("*****-", x, y, c)
		PlotFontLine("-**-**", x, y+1, c)
		PlotFontLine("****-", x+1, y+2, c)
		PlotFontLine("**-", x+1, y+3, c)
		PlotFontLine("-**-", x, y+4, c)
		PlotFontLine("****", x, y+5, c)
	case "q":
		PlotFontLine("-**-**", x, y+1, c)
		PlotFontLine("*--**-", x, y+2, c)
		PlotFontLine("-****", x, y+3, c)
		PlotFontLine("-**-", x+2, y+4, c)
		PlotFontLine("****", x+2, y+5, c)
	case "Q":
		PlotFontLine("-****-", x, y, c)
		PlotFontLine("**--**", x, y+1, c)
		PlotFontLine("** -**", x, y+2, c)
		PlotFontLine("**-***", x, y+3, c)
		PlotFontLine("-****-", x, y+4, c)
		PlotFontLine("-**", x+3, y+5, c)
	case "r":
		PlotFontLine("**-**-", x, y+1, c)
		PlotFontLine("-*****", x, y+2, c)
		PlotFontLine("**--*", x+1, y+3, c)
		PlotFontLine("-**-", x, y+4, c)
		PlotFontLine("****", x, y+5, c)
	case "R":
		PlotFontLine("****-", x, y, c)
		PlotFontLine("-*--*-", x, y+1, c)
		PlotFontLine("*--*-", x+1, y+2, c)
		PlotFontLine("***-", x+1, y+3, c)
		PlotFontLine("-*-**-", x, y+4, c)
		PlotFontLine("**--**", x, y+5, c)
	case "s":
		PlotFontLine("-*****", x, y+1, c)
		PlotFontLine("**-", x, y+2, c)
		PlotFontLine("-****-", x, y+3, c)
		PlotFontLine("-**", x+3, y+4, c)
		PlotFontLine("*****-", x, y+5, c)
	case "S":
		PlotFontLine("-****-", x, y, c)
		PlotFontLine("**--**", x, y+1, c)
		PlotFontLine("-***-", x, y+2, c)
		PlotFontLine("-**-", x+2, y+3, c)
		PlotFontLine("**--**", x, y+4, c)
		PlotFontLine("-****-", x, y+5, c)
	case "t":
		PlotFontLine("-*", x+1, y, c)
		PlotFontLine("-**-", x, y+1, c)
		PlotFontLine("****", x, y+2, c)
		PlotFontLine("-**-", x, y+3, c)
		PlotFontLine("**-*", x+1, y+4, c)
		PlotFontLine("-**-", x+1, y+5, c)
	case "T":
		PlotFontLine("******", x, y, c)
		PlotFontLine("*-**-*", x, y+1, c)
		PlotFontLine("**", x+2, y+2, c)
		PlotFontLine("**", x+2, y+3, c)
		PlotFontLine("-**-", x+1, y+4, c)
		PlotFontLine("****", x+1, y+5, c)
	case "u":
		PlotFontLine("** **", x, y+1, c)
		PlotFontLine("** **", x, y+2, c)
		PlotFontLine("** **", x, y+3, c)
		PlotFontLine("**-**-", x, y+4, c)
		PlotFontLine("-**-**", x, y+5, c)
	case "U":
		PlotFontLine("**  **", x, y, c)
		PlotFontLine("**  **", x, y+1, c)
		PlotFontLine("**  **", x, y+2, c)
		PlotFontLine("**  **", x, y+3, c)
		PlotFontLine("**--**", x, y+4, c)
		PlotFontLine("-****-", x, y+5, c)
	case "v":
		PlotFontLine("**  **", x, y+1, c)
		PlotFontLine("**  **", x, y+2, c)
		PlotFontLine("**--**", x, y+3, c)
		PlotFontLine("-****-", x, y+4, c)
		PlotFontLine("-**-", x+1, y+5, c)
	case "V":
		PlotFontLine("**  **", x, y, c)
		PlotFontLine("**  **", x, y+1, c)
		PlotFontLine("**  **", x, y+2, c)
		PlotFontLine("**--**", x, y+3, c)
		PlotFontLine("-****-", x, y+4, c)
		PlotFontLine("-**-", x+1, y+5, c)
	case "w":
		PlotFontLine("*   *", x+1, y+1, c)
		PlotFontLine("*- -*", x+1, y+2, c)
		PlotFontLine("*-*-*", x+1, y+3, c)
		PlotFontLine("*-*-*", x+1, y+4, c)
		PlotFontLine("-*-*-", x+1, y+5, c)
	case "W":
		PlotFontLine("*   *", x+1, y, c)
		PlotFontLine("*- -*", x+1, y+1, c)
		PlotFontLine("*- -*", x+1, y+2, c)
		PlotFontLine("*-*-*", x+1, y+3, c)
		PlotFontLine("**-**", x+1, y+4, c)
		PlotFontLine("-*-*-", x+1, y+5, c)
	case "x":
		PlotFontLine("**--**", x, y+1, c)
		PlotFontLine("-****-", x, y+2, c)
		PlotFontLine("-**-", x+1, y+3, c)
		PlotFontLine("-****-", x, y+4, c)
		PlotFontLine("**--**", x, y+5, c)
	case "X":
		PlotFontLine("**--**", x, y, c)
		PlotFontLine("-****-", x, y+1, c)
		PlotFontLine("-**-", x+1, y+2, c)
		PlotFontLine("-**-", x+1, y+3, c)
		PlotFontLine("-****-", x, y+4, c)
		PlotFontLine("**--**", x, y+5, c)
	case "y":
		PlotFontLine("**  **", x, y+1, c)
		PlotFontLine("**--**", x, y+2, c)
		PlotFontLine("-****-", x, y+3, c)
		PlotFontLine("-*", x+4, y+4, c)
		PlotFontLine("*****-", x, y+5, c)
	case "Y":
		PlotFontLine("**  **", x, y, c)
		PlotFontLine("**--**", x, y+1, c)
		PlotFontLine("-****-", x, y+2, c)
		PlotFontLine("-**-", x+1, y+3, c)
		PlotFontLine("-**-", x+1, y+4, c)
		PlotFontLine("****", x+1, y+5, c)
	case "z":
		PlotFontLine("******", x, y+1, c)
		PlotFontLine("*--**-", x, y+2, c)
		PlotFontLine("-**-", x+1, y+3, c)
		PlotFontLine("-**--*", x, y+4, c)
		PlotFontLine("******", x, y+5, c)
	case "Z":
		PlotFontLine("******", x, y, c)
		PlotFontLine("*- -**", x, y+1, c)
		PlotFontLine("-**-", x+2, y+2, c)
		PlotFontLine("-**-", x+1, y+3, c)
		PlotFontLine("-**--*", x, y+4, c)
		PlotFontLine("******", x, y+5, c)
		// These weirdos are circles used for turtle graphics
	case "æ":
		PlotFontLine("****-", x, y+1, c)
		PlotFontLine("-*-*", x+1, y+2, c)
		PlotFontLine("-***-", x, y+3, c)
		PlotFontLine("*-*-", x, y+4, c)
		PlotFontLine("-****", x, y+5, c)
	case "Æ":
		PlotFontLine("-*****", x, y, c)
		PlotFontLine("**-**-", x, y+1, c)
		PlotFontLine("******", x, y+2, c)
		PlotFontLine("**-**-", x, y+3, c)
		PlotFontLine("** **-", x, y+4, c)
		PlotFontLine("** ***", x, y+5, c)
	case "ø":
		PlotFontLine("-***-*", x, y+1, c)
		PlotFontLine("*--**-", x, y+2, c)
		PlotFontLine("*-**-*", x, y+3, c)
		PlotFontLine("-**--*", x, y+4, c)
		PlotFontLine("*-***-", x, y+5, c)
	case "Ø":
		PlotFontLine("-***-*", x, y, c)
		PlotFontLine("*--**-", x, y+1, c)
		PlotFontLine("*-**-*", x, y+2, c)
		PlotFontLine("*-**-*", x, y+3, c)
		PlotFontLine("-**--*", x, y+4, c)
		PlotFontLine("*-***-", x, y+5, c)
	case "å":
		PlotFontLine("-**-", x+1, y, c)
		PlotFontLine("***-", x+1, y+1, c)
		PlotFontLine("--**", x+1, y+2, c)
		PlotFontLine("-****", x, y+3, c)
		PlotFontLine("**-**-", x, y+4, c)
		PlotFontLine("-**-**", x, y+5, c)
	case "Å":
		PlotFontLine("**", x+2, y, c)
		PlotFontLine("--", x+2, y+1, c)
		PlotFontLine("-****-", x, y+2, c)
		PlotFontLine("**--**", x, y+3, c)
		PlotFontLine("******", x, y+4, c)
		PlotFontLine("**--**", x, y+5, c)
	case ".":
		PlotFontLine("**-", x+1, y+4, c)
		PlotFontLine("-**", x, y+5, c)
	case ":":
		PlotFontLine("**-", x+1, y, c)
		PlotFontLine("-**", x, y+1, c)
		PlotFontLine("**-", x+1, y+4, c)
		PlotFontLine("-**", x, y+5, c)
	case "":
		PlotFontLine("**-", x+1, y, c)
		PlotFontLine("-**", x, y+1, c)
		PlotFontLine("-*", x+1, y+4, c)
		PlotFontLine("*-", x+1, y+5, c)
	case ",":
		PlotFontLine("-*", x+1, y+4, c)
		PlotFontLine("*-", x+1, y+5, c)
	case "'":
		PlotFontLine("-*", x+1, y, c)
		PlotFontLine("*-", x+1, y+1, c)
	case "\"":
		PlotFontLine("-* -*", x, y, c)
		PlotFontLine("*- *-", x, y+1, c)
	case "*":
		PlotFontLine("-*-", x, y, c)
		PlotFontLine("-*-", x+1, y+1, c)
		PlotFontLine("-******", x-3, y+2, c)
		PlotFontLine("-*-", x+1, y+3, c)
		PlotFontLine("-*-", x, y+4, c)
	case "+":
		PlotFontLine("  **   ", x, y+2, c)
		PlotFontLine("-****-", x, y+3, c)
		PlotFontLine("  **   ", x, y+4, c)
	case "!":
		PlotFontLine("**", x+1, y, c)
		PlotFontLine("-**-", x, y+1, c)
		PlotFontLine("-**-", x, y+2, c)
		PlotFontLine("**", x+1, y+3, c)
		PlotFontLine("--", x+1, y+4, c)
		PlotFontLine("**", x+1, y+5, c)
	case "?":
		PlotFontLine("-****-", x, y, c)
		PlotFontLine("**--**", x, y+1, c)
		PlotFontLine("-**-", x+2, y+2, c)
		PlotFontLine("**-", x+2, y+3, c)
		PlotFontLine("--", x+2, y+4, c)
		PlotFontLine("**", x+2, y+5, c)
	case "-":
		PlotFontLine("-****-", x, y+3, c)
	case "=":
		PlotFontLine("-****-", x, y+2, c)
		PlotFontLine("-****-", x, y+4, c)
	case "_":
		PlotFontLine("-****-", x, y+5, c)
	case "/":
		PlotFontLine("*", x+4, y+1, c)
		PlotFontLine("*-", x+3, y+2, c)
		PlotFontLine("*-", x+2, y+3, c)
		PlotFontLine("*-", x+1, y+4, c)
		PlotFontLine("*-", x+0, y+5, c)
	case "1":
		PlotFontLine("-**", x+1, y, c)
		PlotFontLine("***", x+1, y+1, c)
		PlotFontLine("-**", x+1, y+2, c)
		PlotFontLine("**", x+2, y+3, c)
		PlotFontLine("**-", x+2, y+4, c)
		PlotFontLine("****", x+1, y+5, c)
	case "2":
		PlotFontLine("-****-", x, y, c)
		PlotFontLine("*- -**", x, y+1, c)
		PlotFontLine("-**-", x+2, y+2, c)
		PlotFontLine("-**-", x+1, y+3, c)
		PlotFontLine("-**--*", x, y+4, c)
		PlotFontLine("******", x, y+5, c)
	case "3":
		PlotFontLine("-****-", x, y, c)
		PlotFontLine("**--**", x, y+1, c)
		PlotFontLine("**-", x+3, y+2, c)
		PlotFontLine("-**", x+3, y+3, c)
		PlotFontLine("**--**", x, y+4, c)
		PlotFontLine("-****-", x, y+5, c)
	case "4":
		PlotFontLine("-***", x+1, y, c)
		PlotFontLine("-*-**", x, y+1, c)
		PlotFontLine("*--**-", x, y+2, c)
		PlotFontLine("******", x, y+3, c)
		PlotFontLine("-**-", x+2, y+4, c)
		PlotFontLine("****", x+2, y+5, c)
	case "5":
		PlotFontLine("******", x, y, c)
		PlotFontLine("**-", x, y+1, c)
		PlotFontLine("*****-", x, y+2, c)
		PlotFontLine("-**", x+3, y+3, c)
		PlotFontLine("**--**", x, y+4, c)
		PlotFontLine("-****-", x, y+5, c)
	case "6":
		PlotFontLine("-***", x+1, y, c)
		PlotFontLine("-**-", x, y+1, c)
		PlotFontLine("**-", x, y+2, c)
		PlotFontLine("*****-", x, y+3, c)
		PlotFontLine("**--**", x, y+4, c)
		PlotFontLine("-****-", x, y+5, c)
	case "7":
		PlotFontLine("******", x, y, c)
		PlotFontLine("*- -**", x, y+1, c)
		PlotFontLine("-**", x+3, y+2, c)
		PlotFontLine("-**-", x+2, y+3, c)
		PlotFontLine("**-", x+2, y+4, c)
		PlotFontLine("**", x+2, y+5, c)
	case "8":
		PlotFontLine("-****-", x, y, c)
		PlotFontLine("**--**", x, y+1, c)
		PlotFontLine("-****-", x, y+2, c)
		PlotFontLine("**--**", x, y+3, c)
		PlotFontLine("**--**", x, y+4, c)
		PlotFontLine("-****-", x, y+5, c)
	case "9":
		PlotFontLine("-****-", x, y, c)
		PlotFontLine("**--**", x, y+1, c)
		PlotFontLine("-*****", x, y+2, c)
		PlotFontLine("-**", x+3, y+3, c)
		PlotFontLine("-**-", x+2, y+4, c)
		PlotFontLine("-***-", x, y+5, c)
	case "0":
		PlotFontLine("-****-", x, y, c)
		PlotFontLine("**--**", x, y+1, c)
		PlotFontLine("**--**", x, y+2, c)
		PlotFontLine("**--**", x, y+3, c)
		PlotFontLine("**--**", x, y+4, c)
		PlotFontLine("-****-", x, y+5, c)
	case "(":
		PlotFontLine("-***", x+2, y, c)
		PlotFontLine("**-", x+2, y+1, c)
		PlotFontLine("**-", x+1, y+2, c)
		PlotFontLine("**-", x+1, y+3, c)
		PlotFontLine("**-", x+2, y+4, c)
		PlotFontLine("-***", x+2, y+5, c)
	case ")":
		PlotFontLine("***-", x, y, c)
		PlotFontLine("-**", x+1, y+1, c)
		PlotFontLine("-**", x+2, y+2, c)
		PlotFontLine("-**", x+2, y+3, c)
		PlotFontLine("-**", x+1, y+4, c)
		PlotFontLine("***-", x, y+5, c)
	}
}
